### ISSUE TITLE
Test Program 8 - Interrupts für TMR0, RB0 (INT) und RB4-7

### ISSUE THREAD

**Issue by tobi4321** [tobi4321/Pic_Simulator#20]

**Comment by EinToni** [comment]
In Programm zeile 14 wird ein R (== 0x52) geschrieben. Am Ende steht im Programm aber das eine 0x53 da stehen sollte.
Ansonten funktioniert alles

**Comment by tobi4321** [comment]
Frage beantwortet. Fehler im Kommentar vom Testprogramm 
R wird geschrieben und damit wird 0x52 am Ende erwartet.
